[package]
name        = "legion-web"
version.workspace   = true
edition.workspace   = true
authors.workspace   = true
license.workspace   = true

[[bin]]
name = "legion-web"
path = "src/main.rs"

[dependencies]
legion-core      = { path = "../legion-core" }
legion-poncho    = { path = "../legion-poncho" }
axum             = { workspace = true }
tower-http       = { workspace = true }
tokio            = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
anyhow           = { workspace = true }
tracing          = { workspace = true }
tracing-subscriber = { workspace = true }
clap             = { workspace = true }
open             = { workspace = true }
chrono           = { workspace = true }
sysinfo          = { workspace = true }

[dev-dependencies]
tower            = { workspace = true }
tempfile         = { workspace = true }
